### ISSUE TITLE
Add screenshot to README

### ISSUE THREAD

**Issue by halo** [SpencerCurtis/GYI#2]
I know it sounds a bit silly, but I spend about 5-10 seconds on a github page to decide whether or not to choose a tool. A screenshot would be really helpful so I wouldn't have to compile the entire product first. 

Or maybe a [homebrew cask](https://github.com/caskroom/homebrew-cask) would make this process easier/faster.

**Comment by SpencerCurtis** [comment]
No, that’s a great idea. I’ll do that later today. Thanks for the suggestion!

**Comment by SpencerCurtis** [comment]
A gif has been added showing use of GYI.

**Comment by halo** [comment]
It's beautiful! Thank you
